### ISSUE TITLE
Mini apps not working with repack 5.1.0, Invalid loadShareSync

### ISSUE THREAD

**Issue by Saranya-H-EY** [callstack/super-app-showcase#153]
getting below error for booking, shopping and dashboard while running in ios simulator

console.js:654 Error: Invalid loadShareSync function call from runtime #RUNTIME-006
args: {"hostName":"shopping","sharedPkgName":"react-native"}

**Comment by Saranya-H-EY** [comment]
@jbroma : thanks,  able to see mini apps with 5.1.1 !!

One more question, in DevTools, am able to see files under 'sas-host' but source map is not loaded for mini app's. Any suggestions ?

**Comment by jbroma** [comment]
> [@jbroma](https://github.com/jbroma) : thanks, able to see mini apps with 5.1.1 !!
> 
> One more question, in DevTools, am able to see files under 'sas-host' but source map is not loaded for mini app's. Any suggestions ?

glad it helped! as for the DevTools - aware of it, will try patching that soon 👍
